#!/bin/sh -e

function yes_or_no {
    while true; do
        read -p "$* [y/n]: " yn
        case $yn in
            [Yy]*) return 0  ;;  
            [Nn]*) echo "Aborted" ; return  1 ;;
        esac
    done
}

# compatibility with macos
function _realpath() {
	if which realpath > /dev/null 2>&1 ; then
		realpath "$1"
	elif [[ $1 = /* ]]; then
		echo "$1"
	else
		echo "$PWD/${1#./}"
	fi
}

function _symlinkOrCombine() {
    local _srcPath="$(_realpath ${1})"
    local _dstPath="$(_realpath ${2})"
    local _dstPathSymlink="${_dstPath}/$(basename ${_srcPath})"

    if [[ ! -e "${_dstPath}" ]]; then mkdir -p ${_dstPath}; fi

    # remove symlink to source directory and
    # create symlinks to the files in source path
    if [[ -L "${_dstPathSymlink}" ]]; then
        local _originSrcPath="$(_realpath ${_dstPathSymlink})"
        rm -rf ${_dstPathSymlink}
        mkdir -p ${_dstPathSymlink}
        cp -rsn ${_originSrcPath} ${_dstPath}
    fi

    # decide to create symlink to the whole source directory or
    # create symlinks to the files in source path
    if [[ -d "${_dstPathSymlink}" ]];
        then cp -rsn ${_srcPath} ${_dstPath}
        else ln -s ${_srcPath} ${_dstPathSymlink}
    fi
}

# Prepare Runtime Directory
#
find . -maxdepth 2 -path "./runtime/*" -not -name ".gitignore" -not -name "README*" -exec rm -rf {} \;

find $(_realpath .) -mindepth 3 -maxdepth 3 -type d -regex '.*/[0-9][0-9]-.*/config/.*' -print0 \
| sort -zr \
| while IFS= read -r -d '' _found; do
    _symlinkOrCombine "${_found}" "runtime/config"
done

find $(_realpath .) -mindepth 3 -maxdepth 3 -type d -regex '.*/[0-9][0-9]-.*/docker-images/.*' -print0 \
| sort -zr \
| while IFS= read -r -d '' _found; do
    _symlinkOrCombine "${_found}" "runtime/docker-images"
done

find $(_realpath .) -mindepth 2 -maxdepth 2 -type f -regex '.*/[0-9][0-9]-.*/.env' -print0 \
| sort -z \
| while IFS= read -r -d '' _found; do
    cat ${_found} >> ./runtime/.env
done


# Create Fresh Docker Stack
#
export HOSTNAME

# only delete all when no service has been specified
if [[ -z "$@" ]]; then
    ./docker-compose down --remove-orphans
    yes_or_no "Do you want to remove volumes?" && ./docker-compose down --volumes
else
    ./docker-compose stop "$@"
fi

./docker-compose pull --ignore-pull-failures "$@"
./docker-compose create --force-recreate --build "$@"
./docker-compose start "$@"
