#!/bin/sh -e

_pathPrefix="$1"
if [[ ! -z "${_pathPrefix}" ]];
then
    _pathPrefix="${_pathPrefix}/"
    mkdir -p ${_pathPrefix}
else
    _pathPrefix="./"
fi

_exclude=""

for i in `docker image ls -q`
do _id=$i
    _name="$(docker image inspect --format='{{.RepoTags}}' ${_id} | sed 's|[/:><]|_|g' | sed 's| .*||' | sed 's|^\[||' | sed 's|]$||')"
    if [[ ! -z "${_name}" ]];
    then
	_name=_${_name}
    fi
    
    _file="${_pathPrefix}${_id}${_name}.tar"
    echo -n "${_file}..."
    if [[ -e "${file}" ]];
    then
	docker image save -o ${_file} ${_id}
	echo "SAVED"
    else
	echo "FOUND"
    fi
    _exclude="-not -path ${_file} ${_exclude}" 
done

find ${_pathPrefix} -maxdepth 1 -name "*.tar"  ${_exclude} -exec rm -rfv {} \;
