#!/bin/sh -ex

function _addToFstab() {
    if [[ -z "$(cat /etc/fstab | grep "${1}")" ]];
    then
	if [[ ! -z "$(mount | grep 'on / type .*(ro')" ]];
	then
	    mount -o remount,rw /
	fi

	echo "${1}" >> /etc/fstab
	echo "Entry added to fstab ${1}"
    else
	echo "Entry found in fstab ${1}"
    fi
}

function _addToData() {
    local _source="${1}"
    local _destination="${2}"

    if [[ -z "${_destination}" ]];
    then
	_destination="${DATA_PATH}${_source}"
    fi

    mkdir -p ${_destination}
    chmod --reference=${_source} ${_destination}
    chown --reference=${_source} ${_destination}
}

function _rebindToData() {
    local _source="${1}"
    local _destination="${2}"

    if [[ -z "${_destination}" ]];
    then
	_destination="${DATA_PATH}${_source}"
    fi

    _addToData ${_source} ${_destination}
    _addToFstab "${_destination} ${_source} none bind"
}

if [[ -z "$1" ]];
then
    echo "No Partition provided. Partition is going to be formated!"
    exit
fi

DATA_PATH="/media/data"

systemctl stop docker
systemctl stop docker.socket
systemctl stop containerd
systemctl stop sshd
sleep 30

PARTITION="$1"
PARTITION_ID="$(find -L /dev/disk/by-id -samefile ${PARTITION} | head -n 1)"
if [[ ! -z "$(mount | grep '${DATA_PATH}')" ]];
then
    umount -A ${PARTITION}
fi

mkfs.ext4 ${PARTITION_ID}

mkdir -p ${DATA_PATH}
_addToFstab "${PARTITION_ID} ${DATA_PATH} ext4 rw,noinit_itable,noatime,nodiratime,discard 0 2"

mount ${PARTITION_ID} ${DATA_PATH}
rm -rf "${DATA_PATH}/lost+found"

_addToData /etc

_addToData /etc/ssh
_rebindToData /etc/ssh/sshd ${DATA_PATH}/etc/ssh
ssh-keygen -A -f ${DATA_PATH}

_addToData /var

_rebindToData /var/log
_rebindToData /var/tmp
_rebindToData /var/cache

_addToData /var/lib
#_rebindToData /var/lib/systemd
_addToData /var/lib/docker

mkdir -p /var/lib/containerd
chmod --reference=/var/lib/docker /var/lib/containerd
chown --reference=/var/lib/docker /var/lib/containerd
_addToData /var/lib/containerd

_addToData /root

mkdir -p ${DATA_PATH}/etc/homer
cp config.default/homer/config-base.yml ${DATA_PATH}/etc/homer/config-base.yml

systemctl daemon-reload
mount -a

systemctl restart sshd
systemctl restart docker

docker compose create
docker compose restart
